name: CI

on:
  pull_request:
    types: [ready_for_review, opened, synchronize, reopened]
    branches: [ main ]
    paths:
      - 'packages/**'
      - 'package.json'
      - 'package-lock.json'
      - 'tsconfig.json'
      - 'vitest.config.mts'
      - '.github/workflows/**'
  workflow_dispatch:

jobs:
  lint-build-test:
    if: github.event.pull_request.draft != true
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-node@v6
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: Install packages
        run: npm ci

      - name: Build
        run: npm run build

      - name: Check
        run: npm run check

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm run test

      - name: Check publish
        run: npm run check:publish
